fed:
    container_name: fed
    image: learninglayers/fed
    ports:
        - "8082:8082" 
        - "9011/tcp:9011/tcp"
        - "9011/udp:9011/udp"
    env_file:
        - common.env
    net: "host"
